### ISSUE TITLE
Layout when using TextWriter overloads

### ISSUE THREAD

**Issue by fhogberg** [zjklee/Handlebars.CSharp#6]
Tried going to the stream version of Compile() and the following does not work.
Should it work or is this not supported?
```csharp
        [Fact]
        public void CanLoadAViewWithALayout()
        {
            //When a viewengine renders that view
            var handleBars = Handlebars.Create();
            handleBars.RegisterTemplate("somelayout", "layout start\r\n{ { { body} } }\r\nlayout end");
            var templateStream = new StringReader("{{!< somelayout}}This is the body");

            var renderView = handleBars.Compile(templateStream);
            var sb = new StringBuilder();
            var sw = new StringWriter(sb);
            renderView(sw, null);
            var output = sb.ToString();
            
            //Then the correct output should be rendered
            Assert.Equal("layout start\r\nThis is the body\r\nlayout end", output);
        }
```

**Comment by zjklee** [comment]
Unfortunately layout is only supported in `CompileView` scenario. For reference please see [CanLoadAViewWithALayout](https://github.com/zjklee/Handlebars.CSharp/blob/master/source/Handlebars.Test/ViewEngine/ViewEngineTests.cs#L11). Unfortunately `Stream` API is not supported in `CompileView`.

It is possible to add support by extending `ViewEngineFileSystem` base class with something like this:
```csharp
public virtual StringReader GetFileStream(string filename)
{
    return new StringReader(GetFileContent(filename));
}
```
and update usage at [HandlebarsCompiler.CompileView](https://github.com/zjklee/Handlebars.CSharp/blob/master/source/Handlebars/Compiler/HandlebarsCompiler.cs#L48) to use `GetFileStream` instead of `GetFileContent`.
Other implementation options could require breaking changes.

If this functionality is essential for you - you're welcome to create PR. If not I'd address this in next iteration.

**Comment by fhogberg** [comment]
Ok. Thanks for the info.
If i get the time i try to make a PR for it.

**Comment by fhogberg** [comment]
#8 PR Submitted

**Comment by fhogberg** [comment]
Perhaps the PR looks strange but what i needed was a Compile that returned a Action<TextWriter,object> and worked with templates. To read templates from a reader was never a concern.
